#spring.application.name=kiemtra


# Server
server.port=8080

# =====================
# XAMPP MySQL
# =====================
spring.datasource.url=jdbc:mysql://localhost:3306/kiemtra_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8

# File upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
app.upload.path=src/main/resources/static/images/uploads/

# =====================
# Google OAuth2 (Câu 9)
# Thay YOUR_CLIENT_ID và YOUR_CLIENT_SECRET t? Google Cloud Console
# =====================
spring.security.oauth2.client.registration.google.client-id=******
spring.security.oauth2.client.registration.google.client-secret=******
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# ===== LOGGING ?? debug OAuth2 =====
logging.level.com.example.kiemtra=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG